/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.4. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module snn4to3Flat
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire  en // enable
    , input wire  eta_0
    , input wire  eta_1
    , input wire  eta_2
    , input wire  eta_3

      // Outputs
    , output wire  result_0
    , output wire  result_1
    , output wire  result_2
    );
  wire [95:0] c$app_arg;
  wire [2:0] c$app_arg_0;
  reg [95:0] states = {32'sd0,   32'sd0,   32'sd0};
  wire [98:0] results;
  wire [3:0] eta;
  wire [98:0] states_1;
  wire [383:0] c$vec2_0;
  wire [98:0] result_projection;
  wire [2:0] result;

  assign eta = {eta_0,   eta_1,   eta_2,
                eta_3};

  // map begin
  genvar i;
  generate
  for (i=0; i < 3; i = i + 1) begin : map
    wire [32:0] map_in;
    assign map_in = results[i*33+:33];
    wire signed [31:0] map_out;
    assign map_out = $signed(map_in[32:1]);


    assign c$app_arg[i*32+:32] = map_out;
  end
  endgenerate
  // map end

  // map begin
  genvar i_0;
  generate
  for (i_0=0; i_0 < 3; i_0 = i_0 + 1) begin : map_0
    wire [32:0] map_in_0;
    assign map_in_0 = results[i_0*33+:33];
    wire  map_out_0;
    assign map_out_0 = map_in_0[0:0];


    assign c$app_arg_0[i_0*1+:1] = map_out_0;
  end
  endgenerate
  // map end

  assign states_1 = {c$app_arg,   c$app_arg_0};

  // register begin
  always @(posedge clk or  posedge  rst) begin : states_register
    if ( rst) begin
      states <= {32'sd0,   32'sd0,   32'sd0};
    end else if (en) begin
      states <= states_1[98:3];
    end
  end
  // register end

  assign c$vec2_0 = {{32'sd32768,   32'sd19660,
                      -32'sd13107,   32'sd26214},   {32'sd6553,
                                                     32'sd39321,   32'sd13107,   -32'sd6553},
                     {-32'sd19660,   32'sd13107,   32'sd32768,
                      32'sd19660}};

  // zipWith start
  genvar i_3;
  generate
  for (i_3 = 0; i_3 < 3; i_3 = i_3 + 1) begin : zipWith_1
    wire signed [31:0] zipWith_in1_1;
    assign zipWith_in1_1 = states[i_3*32+:32];
    wire [127:0] zipWith_in2_1;
    assign zipWith_in2_1 = c$vec2_0[i_3*128+:128];
    wire [32:0] c$n_1;
    wire signed [31:0] result_7;
    wire signed [31:0] c$case_alt;
    wire [31:0] \r' ;
    wire [32:0] \c$r'_app_arg ;
    wire signed [32:0] r;
    wire  fired;
    wire [32:0] result_6;
    wire signed [31:0] c$app_arg_1;
    wire [159:0] ws;
    wire [127:0] ws1;
    wire [127:0] c$ws1_app_arg;
    wire signed [31:0] result_8;
    wire signed [31:0] c$case_alt_0;
    wire [16:0] c$app_arg_2;
    wire [15:0] c$app_arg_3;
    wire [15:0] rL;
    wire [47:0] rR;
    wire [63:0] ds3;
    wire signed [63:0] c$ds3_app_arg;
    wire [31:0] c$bv;
    wire [31:0] c$bv_0;
    wire [31:0] c$bv_1;
    wire [32:0] \r'_projection ;
    wire [127:0] c$vec2;
    wire [47:0] c$bv_5;
    wire [47:0] c$bv_6;
    assign c$n_1 = result_6;

    assign c$bv = (\r' );

    assign result_7 = ((( \c$r'_app_arg [33-1] ) ^ ( c$bv[32-1] )) == 1'b0) ? ($signed(\r' )) : c$case_alt;

    assign c$bv_0 = (($unsigned(result_8)));

    assign c$bv_1 = (($unsigned(($signed(ws[32-1:0])))));

    assign c$case_alt = ((( c$bv_0[32-1] ) & ( c$bv_1[32-1] )) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign \r'_projection  = \c$r'_app_arg ;

    assign \r'  = \r'_projection [31:0];

    assign \c$r'_app_arg  = ($unsigned(r));

    assign r = result_8 + ($signed(ws[32-1:0]));

    assign fired = result_7 >= 32'sd65536;

    assign result_6 = {c$app_arg_1,   fired};

    assign c$app_arg_1 = fired ? 32'sd0 : result_7;

    assign ws = {32'sd0,   ws1};

    assign c$vec2 = (ws[160-1 : 32]);

    // zipWith start
    genvar i_1;

    for (i_1 = 0; i_1 < 4; i_1 = i_1 + 1) begin : zipWith
      wire signed [31:0] zipWith_in1;
      assign zipWith_in1 = c$ws1_app_arg[i_1*32+:32];
      wire signed [31:0] zipWith_in2;
      assign zipWith_in2 = c$vec2[i_1*32+:32];
      wire signed [31:0] c$n;
      wire signed [31:0] result_9;
    wire signed [31:0] c$case_alt_4;
    wire [31:0] \r'_1 ;
    wire [32:0] \c$r'_app_arg_0 ;
    wire signed [32:0] r_0;
    wire [31:0] c$bv_2;
    wire [31:0] c$bv_3;
    wire [31:0] c$bv_4;
    wire [32:0] \r'_projection_0 ;
    assign c$n = result_9;

    assign c$bv_2 = (\r'_1 );

    assign result_9 = ((( \c$r'_app_arg_0 [33-1] ) ^ ( c$bv_2[32-1] )) == 1'b0) ? ($signed(\r'_1 )) : c$case_alt_4;

    assign c$bv_3 = (($unsigned(zipWith_in2)));

    assign c$bv_4 = (($unsigned(zipWith_in1)));

    assign c$case_alt_4 = ((( c$bv_3[32-1] ) & ( c$bv_4[32-1] )) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign \r'_projection_0  = \c$r'_app_arg_0 ;

    assign \r'_1  = \r'_projection_0 [31:0];

    assign \c$r'_app_arg_0  = ($unsigned(r_0));

    assign r_0 = zipWith_in2 + zipWith_in1;


      assign ws1[i_1*32+:32] = c$n;
    end

    // zipWith end

    // zipWith start
    genvar i_2;

    for (i_2 = 0; i_2 < 4; i_2 = i_2 + 1) begin : zipWith_0
      wire signed [31:0] zipWith_in1_0;
      assign zipWith_in1_0 = zipWith_in2_1[i_2*32+:32];
      wire  zipWith_in2_0;
      assign zipWith_in2_0 = eta[i_2*1+:1];
      wire signed [31:0] c$n_0;
      wire signed [31:0] result_10;
    assign c$n_0 = result_10;

    assign result_10 = zipWith_in2_0 ? zipWith_in1_0 : 32'sd0;


      assign c$ws1_app_arg[i_2*32+:32] = c$n_0;
    end

    // zipWith end

    assign c$bv_5 = (rR >> (64'sd16));

    assign result_8 = (((~ (| (c$app_arg_2))) | (& (c$app_arg_2))) == 1'b1) ? ($signed((c$bv_5[0+:32]))) : c$case_alt_0;

    assign c$case_alt_0 = (( c$app_arg_3[16-1] ) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign c$bv_6 = (rR);

    assign c$app_arg_2 = ({((( c$bv_6[48-1] ))),c$app_arg_3});

    assign c$app_arg_3 = rL;

    assign rL = ds3[63:48];

    assign rR = ds3[47:0];

    assign ds3 = (($unsigned(c$ds3_app_arg)));

    assign c$ds3_app_arg = 32'sd58982 * zipWith_in1_1;


    assign results[i_3*33+:33] = c$n_1;
  end
  endgenerate
  // zipWith end

  assign result_projection = {c$app_arg,
                              c$app_arg_0};

  assign result = result_projection[2:0];

  assign result_0 = result[2:2];

  assign result_1 = result[1:1];

  assign result_2 = result[0:0];


endmodule

