/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.4. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module snn32to16to8Flat
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire  en // enable
    , input wire  eta_0
    , input wire  eta_1
    , input wire  eta_2
    , input wire  eta_3
    , input wire  eta_4
    , input wire  eta_5
    , input wire  eta_6
    , input wire  eta_7
    , input wire  eta_8
    , input wire  eta_9
    , input wire  eta_10
    , input wire  eta_11
    , input wire  eta_12
    , input wire  eta_13
    , input wire  eta_14
    , input wire  eta_15
    , input wire  eta_16
    , input wire  eta_17
    , input wire  eta_18
    , input wire  eta_19
    , input wire  eta_20
    , input wire  eta_21
    , input wire  eta_22
    , input wire  eta_23
    , input wire  eta_24
    , input wire  eta_25
    , input wire  eta_26
    , input wire  eta_27
    , input wire  eta_28
    , input wire  eta_29
    , input wire  eta_30
    , input wire  eta_31

      // Outputs
    , output wire  c$ds_app_arg_0
    , output wire  c$ds_app_arg_1
    , output wire  c$ds_app_arg_2
    , output wire  c$ds_app_arg_3
    , output wire  c$ds_app_arg_4
    , output wire  c$ds_app_arg_5
    , output wire  c$ds_app_arg_6
    , output wire  c$ds_app_arg_7
    );
  // /Users/jake/EMPIRE/projects/ongoing/2026_039/CategoricalSNN.hs/synthesis/TopEntities.hs:316:1-16
  wire [511:0] c$results1_app_arg;
  wire [255:0] result;
  // /Users/jake/EMPIRE/projects/ongoing/2026_039/CategoricalSNN.hs/synthesis/TopEntities.hs:316:1-16
  wire [511:0] c$ds_app_arg_16;
  // /Users/jake/EMPIRE/projects/ongoing/2026_039/CategoricalSNN.hs/synthesis/TopEntities.hs:316:1-16
  wire [255:0] c$ds_app_arg_17;
  // /Users/jake/EMPIRE/projects/ongoing/2026_039/CategoricalSNN.hs/synthesis/TopEntities.hs:316:1-16
  wire [511:0] s1;
  // /Users/jake/EMPIRE/projects/ongoing/2026_039/CategoricalSNN.hs/synthesis/TopEntities.hs:316:1-16
  wire [255:0] s2;
  // /Users/jake/EMPIRE/projects/ongoing/2026_039/CategoricalSNN.hs/synthesis/TopEntities.hs:316:1-16
  reg [767:0] ds = {{32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,
  32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,
  32'sd0},   {32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,
              32'sd0,   32'sd0}};
  // /Users/jake/EMPIRE/projects/ongoing/2026_039/CategoricalSNN.hs/synthesis/TopEntities.hs:316:1-16
  wire [15:0] midSpikes;
  // /Users/jake/EMPIRE/projects/ongoing/2026_039/CategoricalSNN.hs/synthesis/TopEntities.hs:316:1-16
  wire [527:0] results1;
  // /Users/jake/EMPIRE/projects/ongoing/2026_039/CategoricalSNN.hs/synthesis/TopEntities.hs:316:1-16
  wire [263:0] results2;
  wire [31:0] eta;
  wire [16383:0] c$vec;
  wire [4095:0] c$vec_0;
  wire [7:0] c$ds_app_arg;

  assign eta = {eta_0,   eta_1,   eta_2,
                eta_3,   eta_4,   eta_5,   eta_6,   eta_7,
                eta_8,   eta_9,   eta_10,   eta_11,   eta_12,
                eta_13,   eta_14,   eta_15,   eta_16,
                eta_17,   eta_18,   eta_19,   eta_20,
                eta_21,   eta_22,   eta_23,   eta_24,
                eta_25,   eta_26,   eta_27,   eta_28,
                eta_29,   eta_30,   eta_31};

  assign c$vec = ({16 {({32 {32'sd4096}})}});

  // map begin
  genvar i_1;
  generate
  for (i_1=0; i_1 < 16; i_1 = i_1 + 1) begin : map
    wire [1023:0] map_in;
    assign map_in = c$vec[i_1*1024+:1024];
    wire signed [31:0] map_out;
    // /Users/jake/EMPIRE/projects/ongoing/2026_039/CategoricalSNN.hs/synthesis/TopEntities.hs:316:1-16
    wire [1055:0] ws1;
    // /Users/jake/EMPIRE/projects/ongoing/2026_039/CategoricalSNN.hs/synthesis/TopEntities.hs:316:1-16
    wire [1023:0] ws2;
    wire signed [31:0] result_0;
    // /Users/jake/EMPIRE/projects/ongoing/2026_039/CategoricalSNN.hs/synthesis/TopEntities.hs:316:1-16
    wire [1023:0] c$ws2_app_arg;
    wire [1023:0] c$vec2;
    assign map_out = result_0;

    assign ws1 = {32'sd0,   ws2};

    assign c$vec2 = (ws1[1056-1 : 32]);

    // zipWith start
    genvar i;

    for (i = 0; i < 32; i = i + 1) begin : zipWith
      wire signed [31:0] zipWith_in1;
      assign zipWith_in1 = c$ws2_app_arg[i*32+:32];
      wire signed [31:0] zipWith_in2;
      assign zipWith_in2 = c$vec2[i*32+:32];
      wire signed [31:0] c$n;
      wire signed [31:0] result_1;
    wire signed [31:0] c$case_alt;
    wire [31:0] \r' ;
    wire [32:0] \c$r'_app_arg ;
    wire signed [32:0] r;
    wire [31:0] c$bv;
    wire [31:0] c$bv_0;
    wire [31:0] c$bv_1;
    wire [32:0] \r'_projection ;
    assign c$n = result_1;

    assign c$bv = (\r' );

    assign result_1 = ((( \c$r'_app_arg [33-1] ) ^ ( c$bv[32-1] )) == 1'b0) ? ($signed(\r' )) : c$case_alt;

    assign c$bv_0 = (($unsigned(zipWith_in2)));

    assign c$bv_1 = (($unsigned(zipWith_in1)));

    assign c$case_alt = ((( c$bv_0[32-1] ) & ( c$bv_1[32-1] )) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign \r'_projection  = \c$r'_app_arg ;

    assign \r'  = \r'_projection [31:0];

    assign \c$r'_app_arg  = ($unsigned(r));

    assign r = zipWith_in2 + zipWith_in1;


      assign ws2[i*32+:32] = c$n;
    end

    // zipWith end

    assign result_0 = $signed(ws1[32-1:0]);

    // zipWith start
    genvar i_0;

    for (i_0 = 0; i_0 < 32; i_0 = i_0 + 1) begin : zipWith_0
      wire signed [31:0] zipWith_in1_0;
      assign zipWith_in1_0 = map_in[i_0*32+:32];
      wire  zipWith_in2_0;
      assign zipWith_in2_0 = eta[i_0*1+:1];
      wire signed [31:0] c$n_0;
      wire signed [31:0] result_2;
    assign c$n_0 = result_2;

    assign result_2 = zipWith_in2_0 ? zipWith_in1_0 : 32'sd0;


      assign c$ws2_app_arg[i_0*32+:32] = c$n_0;
    end

    // zipWith end


    assign c$results1_app_arg[i_1*32+:32] = map_out;
  end
  endgenerate
  // map end

  assign c$vec_0 = ({8 {({16 {32'sd8192}})}});

  // map begin
  genvar i_4;
  generate
  for (i_4=0; i_4 < 8; i_4 = i_4 + 1) begin : map_0
    wire [511:0] map_in_0;
    assign map_in_0 = c$vec_0[i_4*512+:512];
    wire signed [31:0] map_out_0;
    // /Users/jake/EMPIRE/projects/ongoing/2026_039/CategoricalSNN.hs/synthesis/TopEntities.hs:316:1-16
    wire [543:0] ws1_1;
    // /Users/jake/EMPIRE/projects/ongoing/2026_039/CategoricalSNN.hs/synthesis/TopEntities.hs:316:1-16
    wire [511:0] ws2_0;
    wire signed [31:0] result_3;
    // /Users/jake/EMPIRE/projects/ongoing/2026_039/CategoricalSNN.hs/synthesis/TopEntities.hs:316:1-16
    wire [511:0] c$ws2_app_arg_0;
    wire [511:0] c$vec2_0;
    assign map_out_0 = result_3;

    assign ws1_1 = {32'sd0,   ws2_0};

    assign c$vec2_0 = (ws1_1[544-1 : 32]);

    // zipWith start
    genvar i_2;

    for (i_2 = 0; i_2 < 16; i_2 = i_2 + 1) begin : zipWith_1
      wire signed [31:0] zipWith_in1_1;
      assign zipWith_in1_1 = c$ws2_app_arg_0[i_2*32+:32];
      wire signed [31:0] zipWith_in2_1;
      assign zipWith_in2_1 = c$vec2_0[i_2*32+:32];
      wire signed [31:0] c$n_1;
      wire signed [31:0] result_4;
    wire signed [31:0] c$case_alt_3;
    wire [31:0] \r'_1 ;
    wire [32:0] \c$r'_app_arg_0 ;
    wire signed [32:0] r_0;
    wire [31:0] c$bv_2;
    wire [31:0] c$bv_3;
    wire [31:0] c$bv_4;
    wire [32:0] \r'_projection_0 ;
    assign c$n_1 = result_4;

    assign c$bv_2 = (\r'_1 );

    assign result_4 = ((( \c$r'_app_arg_0 [33-1] ) ^ ( c$bv_2[32-1] )) == 1'b0) ? ($signed(\r'_1 )) : c$case_alt_3;

    assign c$bv_3 = (($unsigned(zipWith_in2_1)));

    assign c$bv_4 = (($unsigned(zipWith_in1_1)));

    assign c$case_alt_3 = ((( c$bv_3[32-1] ) & ( c$bv_4[32-1] )) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign \r'_projection_0  = \c$r'_app_arg_0 ;

    assign \r'_1  = \r'_projection_0 [31:0];

    assign \c$r'_app_arg_0  = ($unsigned(r_0));

    assign r_0 = zipWith_in2_1 + zipWith_in1_1;


      assign ws2_0[i_2*32+:32] = c$n_1;
    end

    // zipWith end

    assign result_3 = $signed(ws1_1[32-1:0]);

    // zipWith start
    genvar i_3;

    for (i_3 = 0; i_3 < 16; i_3 = i_3 + 1) begin : zipWith_2
      wire signed [31:0] zipWith_in1_2;
      assign zipWith_in1_2 = map_in_0[i_3*32+:32];
      wire  zipWith_in2_2;
      assign zipWith_in2_2 = midSpikes[i_3*1+:1];
      wire signed [31:0] c$n_2;
      wire signed [31:0] result_5;
    assign c$n_2 = result_5;

    assign result_5 = zipWith_in2_2 ? zipWith_in1_2 : 32'sd0;


      assign c$ws2_app_arg_0[i_3*32+:32] = c$n_2;
    end

    // zipWith end


    assign result[i_4*32+:32] = map_out_0;
  end
  endgenerate
  // map end

  // map begin
  genvar i_5;
  generate
  for (i_5=0; i_5 < 16; i_5 = i_5 + 1) begin : map_1
    wire [32:0] map_in_1;
    assign map_in_1 = results1[i_5*33+:33];
    wire signed [31:0] map_out_1;
    assign map_out_1 = $signed(map_in_1[32:1]);


    assign c$ds_app_arg_16[i_5*32+:32] = map_out_1;
  end
  endgenerate
  // map end

  // map begin
  genvar i_6;
  generate
  for (i_6=0; i_6 < 8; i_6 = i_6 + 1) begin : map_2
    wire [32:0] map_in_2;
    assign map_in_2 = results2[i_6*33+:33];
    wire signed [31:0] map_out_2;
    assign map_out_2 = $signed(map_in_2[32:1]);


    assign c$ds_app_arg_17[i_6*32+:32] = map_out_2;
  end
  endgenerate
  // map end

  // map begin
  genvar i_7;
  generate
  for (i_7=0; i_7 < 8; i_7 = i_7 + 1) begin : map_3
    wire [32:0] map_in_3;
    assign map_in_3 = results2[i_7*33+:33];
    wire  map_out_3;
    assign map_out_3 = map_in_3[0:0];


    assign c$ds_app_arg[i_7*1+:1] = map_out_3;
  end
  endgenerate
  // map end

  assign s1 = ds[767:256];

  assign s2 = ds[255:0];

  // register begin
  always @(posedge clk or  posedge  rst) begin : ds_register
    if ( rst) begin
      ds <= {{32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,
    32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,
    32'sd0},   {32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,
                32'sd0,   32'sd0}};
    end else if (en) begin
      ds <= {c$ds_app_arg_16,   c$ds_app_arg_17};
    end
  end
  // register end

  // map begin
  genvar i_8;
  generate
  for (i_8=0; i_8 < 16; i_8 = i_8 + 1) begin : map_4
    wire [32:0] map_in_4;
    assign map_in_4 = results1[i_8*33+:33];
    wire  map_out_4;
    assign map_out_4 = map_in_4[0:0];


    assign midSpikes[i_8*1+:1] = map_out_4;
  end
  endgenerate
  // map end

  // zipWith start
  genvar i_9;
  generate
  for (i_9 = 0; i_9 < 16; i_9 = i_9 + 1) begin : zipWith_3
    wire signed [31:0] zipWith_in1_3;
    assign zipWith_in1_3 = s1[i_9*32+:32];
    wire signed [31:0] zipWith_in2_3;
    assign zipWith_in2_3 = c$results1_app_arg[i_9*32+:32];
    wire [32:0] c$n_3;
    wire signed [31:0] result_7;
    wire signed [31:0] c$case_alt_4;
    wire [31:0] \r'_2 ;
    wire [32:0] \c$r'_app_arg_1 ;
    wire signed [32:0] r_1;
    // /Users/jake/EMPIRE/projects/ongoing/2026_039/CategoricalSNN.hs/synthesis/TopEntities.hs:316:1-16
    wire  fired;
    wire [32:0] result_6;
    wire signed [31:0] c$app_arg;
    wire signed [31:0] result_8;
    wire signed [31:0] c$case_alt_5;
    wire [16:0] c$app_arg_0;
    wire [15:0] c$app_arg_1;
    wire [15:0] rL;
    wire [47:0] rR;
    wire [63:0] ds3;
    wire signed [63:0] c$ds3_app_arg;
    wire [31:0] c$bv_5;
    wire [31:0] c$bv_6;
    wire [31:0] c$bv_7;
    wire [32:0] \r'_projection_1 ;
    wire [47:0] c$bv_8;
    wire [47:0] c$bv_9;
    assign c$n_3 = result_6;

    assign c$bv_5 = (\r'_2 );

    assign result_7 = ((( \c$r'_app_arg_1 [33-1] ) ^ ( c$bv_5[32-1] )) == 1'b0) ? ($signed(\r'_2 )) : c$case_alt_4;

    assign c$bv_6 = (($unsigned(result_8)));

    assign c$bv_7 = (($unsigned(zipWith_in2_3)));

    assign c$case_alt_4 = ((( c$bv_6[32-1] ) & ( c$bv_7[32-1] )) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign \r'_projection_1  = \c$r'_app_arg_1 ;

    assign \r'_2  = \r'_projection_1 [31:0];

    assign \c$r'_app_arg_1  = ($unsigned(r_1));

    assign r_1 = result_8 + zipWith_in2_3;

    assign fired = result_7 >= 32'sd65536;

    assign result_6 = {c$app_arg,   fired};

    assign c$app_arg = fired ? 32'sd0 : result_7;

    assign c$bv_8 = (rR >> (64'sd16));

    assign result_8 = (((~ (| (c$app_arg_0))) | (& (c$app_arg_0))) == 1'b1) ? ($signed((c$bv_8[0+:32]))) : c$case_alt_5;

    assign c$case_alt_5 = (( c$app_arg_1[16-1] ) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign c$bv_9 = (rR);

    assign c$app_arg_0 = ({((( c$bv_9[48-1] ))),c$app_arg_1});

    assign c$app_arg_1 = rL;

    assign rL = ds3[63:48];

    assign rR = ds3[47:0];

    assign ds3 = (($unsigned(c$ds3_app_arg)));

    assign c$ds3_app_arg = 32'sd58982 * zipWith_in1_3;


    assign results1[i_9*33+:33] = c$n_3;
  end
  endgenerate
  // zipWith end

  // zipWith start
  genvar i_10;
  generate
  for (i_10 = 0; i_10 < 8; i_10 = i_10 + 1) begin : zipWith_4
    wire signed [31:0] zipWith_in1_4;
    assign zipWith_in1_4 = s2[i_10*32+:32];
    wire signed [31:0] zipWith_in2_4;
    assign zipWith_in2_4 = result[i_10*32+:32];
    wire [32:0] c$n_4;
    wire signed [31:0] result_10;
    wire signed [31:0] c$case_alt_6;
    wire [31:0] \r'_3 ;
    wire [32:0] \c$r'_app_arg_2 ;
    wire signed [32:0] r_2;
    // /Users/jake/EMPIRE/projects/ongoing/2026_039/CategoricalSNN.hs/synthesis/TopEntities.hs:316:1-16
    wire  fired_0;
    wire [32:0] result_9;
    wire signed [31:0] c$app_arg_5;
    wire signed [31:0] result_11;
    wire signed [31:0] c$case_alt_7;
    wire [16:0] c$app_arg_6;
    wire [15:0] c$app_arg_7;
    wire [15:0] rL_1;
    wire [47:0] rR_1;
    wire [63:0] ds3_0;
    wire signed [63:0] c$ds3_app_arg_0;
    wire [31:0] c$bv_10;
    wire [31:0] c$bv_11;
    wire [31:0] c$bv_12;
    wire [32:0] \r'_projection_2 ;
    wire [47:0] c$bv_13;
    wire [47:0] c$bv_14;
    assign c$n_4 = result_9;

    assign c$bv_10 = (\r'_3 );

    assign result_10 = ((( \c$r'_app_arg_2 [33-1] ) ^ ( c$bv_10[32-1] )) == 1'b0) ? ($signed(\r'_3 )) : c$case_alt_6;

    assign c$bv_11 = (($unsigned(result_11)));

    assign c$bv_12 = (($unsigned(zipWith_in2_4)));

    assign c$case_alt_6 = ((( c$bv_11[32-1] ) & ( c$bv_12[32-1] )) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign \r'_projection_2  = \c$r'_app_arg_2 ;

    assign \r'_3  = \r'_projection_2 [31:0];

    assign \c$r'_app_arg_2  = ($unsigned(r_2));

    assign r_2 = result_11 + zipWith_in2_4;

    assign fired_0 = result_10 >= 32'sd65536;

    assign result_9 = {c$app_arg_5,   fired_0};

    assign c$app_arg_5 = fired_0 ? 32'sd0 : result_10;

    assign c$bv_13 = (rR_1 >> (64'sd16));

    assign result_11 = (((~ (| (c$app_arg_6))) | (& (c$app_arg_6))) == 1'b1) ? ($signed((c$bv_13[0+:32]))) : c$case_alt_7;

    assign c$case_alt_7 = (( c$app_arg_7[16-1] ) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign c$bv_14 = (rR_1);

    assign c$app_arg_6 = ({((( c$bv_14[48-1] ))),c$app_arg_7});

    assign c$app_arg_7 = rL_1;

    assign rL_1 = ds3_0[63:48];

    assign rR_1 = ds3_0[47:0];

    assign ds3_0 = (($unsigned(c$ds3_app_arg_0)));

    assign c$ds3_app_arg_0 = 32'sd58982 * zipWith_in1_4;


    assign results2[i_10*33+:33] = c$n_4;
  end
  endgenerate
  // zipWith end

  assign c$ds_app_arg_0 = c$ds_app_arg[7:7];

  assign c$ds_app_arg_1 = c$ds_app_arg[6:6];

  assign c$ds_app_arg_2 = c$ds_app_arg[5:5];

  assign c$ds_app_arg_3 = c$ds_app_arg[4:4];

  assign c$ds_app_arg_4 = c$ds_app_arg[3:3];

  assign c$ds_app_arg_5 = c$ds_app_arg[2:2];

  assign c$ds_app_arg_6 = c$ds_app_arg[1:1];

  assign c$ds_app_arg_7 = c$ds_app_arg[0:0];


endmodule

