/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.4. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module snn8to4
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire  en // enable
    , input wire  eta_0
    , input wire  eta_1
    , input wire  eta_2
    , input wire  eta_3
    , input wire  eta_4
    , input wire  eta_5
    , input wire  eta_6
    , input wire  eta_7

      // Outputs
    , output wire  result_0
    , output wire  result_1
    , output wire  result_2
    , output wire  result_3
    );
  wire [127:0] c$results_app_arg;
  wire [127:0] c$app_arg;
  wire [3:0] c$app_arg_0;
  reg [127:0] neuronStates = {32'sd0,   32'sd0,   32'sd0,   32'sd0};
  wire [131:0] results;
  wire [7:0] eta;
  wire [1023:0] c$vec;
  wire [131:0] neuronStates_1;
  wire [131:0] result_projection;
  wire [3:0] result;

  assign eta = {eta_0,   eta_1,   eta_2,
                eta_3,   eta_4,   eta_5,   eta_6,   eta_7};

  assign c$vec = {{32'sd32768,   32'sd19660,
                   -32'sd13107,   32'sd26214,   32'sd6553,
                   -32'sd19660,   32'sd13107,   32'sd39321},
                  {32'sd6553,   32'sd39321,   32'sd13107,
                   -32'sd6553,   32'sd26214,   32'sd13107,
                   -32'sd32768,   32'sd19660},   {-32'sd19660,
                                                  32'sd13107,   32'sd32768,   32'sd19660,
                                                  -32'sd6553,   32'sd26214,   32'sd19660,
                                                  -32'sd13107},   {32'sd26214,   -32'sd13107,
                                                                   32'sd39321,   32'sd6553,   32'sd19660,
                                                                   -32'sd26214,   32'sd32768,   32'sd13107}};

  // map begin
  genvar i_1;
  generate
  for (i_1=0; i_1 < 4; i_1 = i_1 + 1) begin : map
    wire [255:0] map_in;
    assign map_in = c$vec[i_1*256+:256];
    wire signed [31:0] map_out;
    wire [287:0] ws;
    wire [255:0] ws1;
    wire signed [31:0] result_8;
    wire [255:0] c$ws1_app_arg;
    wire [255:0] c$vec2;
    assign map_out = result_8;

    assign ws = {32'sd0,   ws1};

    assign c$vec2 = (ws[288-1 : 32]);

    // zipWith start
    genvar i;

    for (i = 0; i < 8; i = i + 1) begin : zipWith
      wire signed [31:0] zipWith_in1;
      assign zipWith_in1 = c$ws1_app_arg[i*32+:32];
      wire signed [31:0] zipWith_in2;
      assign zipWith_in2 = c$vec2[i*32+:32];
      wire signed [31:0] c$n;
      wire signed [31:0] result_9;
    wire signed [31:0] c$case_alt;
    wire [31:0] \r' ;
    wire [32:0] \c$r'_app_arg ;
    wire signed [32:0] r;
    wire [31:0] c$bv;
    wire [31:0] c$bv_0;
    wire [31:0] c$bv_1;
    wire [32:0] \r'_projection ;
    assign c$n = result_9;

    assign c$bv = (\r' );

    assign result_9 = ((( \c$r'_app_arg [33-1] ) ^ ( c$bv[32-1] )) == 1'b0) ? ($signed(\r' )) : c$case_alt;

    assign c$bv_0 = (($unsigned(zipWith_in2)));

    assign c$bv_1 = (($unsigned(zipWith_in1)));

    assign c$case_alt = ((( c$bv_0[32-1] ) & ( c$bv_1[32-1] )) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign \r'_projection  = \c$r'_app_arg ;

    assign \r'  = \r'_projection [31:0];

    assign \c$r'_app_arg  = ($unsigned(r));

    assign r = zipWith_in2 + zipWith_in1;


      assign ws1[i*32+:32] = c$n;
    end

    // zipWith end

    assign result_8 = $signed(ws[32-1:0]);

    // zipWith start
    genvar i_0;

    for (i_0 = 0; i_0 < 8; i_0 = i_0 + 1) begin : zipWith_0
      wire signed [31:0] zipWith_in1_0;
      assign zipWith_in1_0 = map_in[i_0*32+:32];
      wire  zipWith_in2_0;
      assign zipWith_in2_0 = eta[i_0*1+:1];
      wire signed [31:0] c$n_0;
      wire signed [31:0] result_10;
    assign c$n_0 = result_10;

    assign result_10 = zipWith_in2_0 ? zipWith_in1_0 : 32'sd0;


      assign c$ws1_app_arg[i_0*32+:32] = c$n_0;
    end

    // zipWith end


    assign c$results_app_arg[i_1*32+:32] = map_out;
  end
  endgenerate
  // map end

  // map begin
  genvar i_2;
  generate
  for (i_2=0; i_2 < 4; i_2 = i_2 + 1) begin : map_0
    wire [32:0] map_in_0;
    assign map_in_0 = results[i_2*33+:33];
    wire signed [31:0] map_out_0;
    assign map_out_0 = $signed(map_in_0[32:1]);


    assign c$app_arg[i_2*32+:32] = map_out_0;
  end
  endgenerate
  // map end

  // map begin
  genvar i_3;
  generate
  for (i_3=0; i_3 < 4; i_3 = i_3 + 1) begin : map_1
    wire [32:0] map_in_1;
    assign map_in_1 = results[i_3*33+:33];
    wire  map_out_1;
    assign map_out_1 = map_in_1[0:0];


    assign c$app_arg_0[i_3*1+:1] = map_out_1;
  end
  endgenerate
  // map end

  assign neuronStates_1 = {c$app_arg,
                           c$app_arg_0};

  // register begin
  always @(posedge clk or  posedge  rst) begin : neuronStates_register
    if ( rst) begin
      neuronStates <= {32'sd0,   32'sd0,   32'sd0,   32'sd0};
    end else if (en) begin
      neuronStates <= neuronStates_1[131:4];
    end
  end
  // register end

  // zipWith start
  genvar i_4;
  generate
  for (i_4 = 0; i_4 < 4; i_4 = i_4 + 1) begin : zipWith_1
    wire signed [31:0] zipWith_in1_1;
    assign zipWith_in1_1 = neuronStates[i_4*32+:32];
    wire signed [31:0] zipWith_in2_1;
    assign zipWith_in2_1 = c$results_app_arg[i_4*32+:32];
    wire [32:0] c$n_1;
    wire signed [31:0] result_11;
    wire signed [31:0] c$case_alt_4;
    wire [31:0] \r'_1 ;
    wire [32:0] \c$r'_app_arg_0 ;
    wire signed [32:0] r_0;
    wire  fired;
    wire signed [31:0] c$app_arg_1;
    wire signed [31:0] result_12;
    wire signed [31:0] c$case_alt_5;
    wire [16:0] c$app_arg_2;
    wire [15:0] c$app_arg_3;
    wire [15:0] rL;
    wire [47:0] rR;
    wire [63:0] ds3;
    wire signed [63:0] c$ds3_app_arg;
    wire [32:0] c$case_alt_3;
    wire [31:0] c$bv_2;
    wire [31:0] c$bv_3;
    wire [31:0] c$bv_4;
    wire [32:0] \r'_projection_0 ;
    wire [47:0] c$bv_5;
    wire [47:0] c$bv_6;
    assign c$n_1 = c$case_alt_3;

    assign c$bv_2 = (\r'_1 );

    assign result_11 = ((( \c$r'_app_arg_0 [33-1] ) ^ ( c$bv_2[32-1] )) == 1'b0) ? ($signed(\r'_1 )) : c$case_alt_4;

    assign c$bv_3 = (($unsigned(result_12)));

    assign c$bv_4 = (($unsigned(zipWith_in2_1)));

    assign c$case_alt_4 = ((( c$bv_3[32-1] ) & ( c$bv_4[32-1] )) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign \r'_projection_0  = \c$r'_app_arg_0 ;

    assign \r'_1  = \r'_projection_0 [31:0];

    assign \c$r'_app_arg_0  = ($unsigned(r_0));

    assign r_0 = result_12 + zipWith_in2_1;

    assign fired = result_11 >= 32'sd65536;

    assign c$app_arg_1 = fired ? 32'sd0 : result_11;

    assign c$bv_5 = (rR >> (64'sd16));

    assign result_12 = (((~ (| (c$app_arg_2))) | (& (c$app_arg_2))) == 1'b1) ? ($signed((c$bv_5[0+:32]))) : c$case_alt_5;

    assign c$case_alt_5 = (( c$app_arg_3[16-1] ) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign c$bv_6 = (rR);

    assign c$app_arg_2 = ({((( c$bv_6[48-1] ))),c$app_arg_3});

    assign c$app_arg_3 = rL;

    assign rL = ds3[63:48];

    assign rR = ds3[47:0];

    assign ds3 = (($unsigned(c$ds3_app_arg)));

    assign c$ds3_app_arg = 32'sd58982 * zipWith_in1_1;

    assign c$case_alt_3 = {c$app_arg_1,   fired};


    assign results[i_4*33+:33] = c$n_1;
  end
  endgenerate
  // zipWith end

  assign result_projection = {c$app_arg,
                              c$app_arg_0};

  assign result = result_projection[3:0];

  assign result_0 = result[3:3];

  assign result_1 = result[2:2];

  assign result_2 = result[1:1];

  assign result_3 = result[0:0];


endmodule

