/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.4. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module snn4to3to2
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire  en // enable
    , input wire  eta_0
    , input wire  eta_1
    , input wire  eta_2
    , input wire  eta_3

      // Outputs
    , output wire  result_0
    , output wire  result_1
    );
  wire [95:0] c$results_app_arg;
  wire [95:0] c$ds1_app_arg;
  wire [2:0] c$ds1_app_arg_0;
  wire [63:0] c$results_app_arg_0;
  wire [63:0] c$ds2_app_arg;
  wire [1:0] c$ds2_app_arg_0;
  reg [159:0] ds = {{32'sd0,   32'sd0,   32'sd0},   {32'sd0,   32'sd0}};
  wire [95:0] sf;
  wire [63:0] sg;
  wire [98:0] results;
  wire [65:0] results_0;
  wire [3:0] eta;
  wire [383:0] c$vec;
  wire [191:0] c$vec_0;
  wire [161:0] ds_1;
  wire [161:0] result_projection;
  wire [1:0] result;

  assign eta = {eta_0,   eta_1,   eta_2,
                eta_3};

  assign c$vec = {{32'sd32768,   32'sd19660,
                   -32'sd13107,   32'sd26214},   {32'sd6553,
                                                  32'sd39321,   32'sd13107,   -32'sd6553},
                  {-32'sd19660,   32'sd13107,   32'sd32768,
                   32'sd19660}};

  // map begin
  genvar i_1;
  generate
  for (i_1=0; i_1 < 3; i_1 = i_1 + 1) begin : map
    wire [127:0] map_in;
    assign map_in = c$vec[i_1*128+:128];
    wire signed [31:0] map_out;
    wire [159:0] ws;
    wire [127:0] ws1;
    wire signed [31:0] result_4;
    wire [127:0] c$ws1_app_arg;
    wire [127:0] c$vec2;
    assign map_out = result_4;

    assign ws = {32'sd0,   ws1};

    assign c$vec2 = (ws[160-1 : 32]);

    // zipWith start
    genvar i;

    for (i = 0; i < 4; i = i + 1) begin : zipWith
      wire signed [31:0] zipWith_in1;
      assign zipWith_in1 = c$ws1_app_arg[i*32+:32];
      wire signed [31:0] zipWith_in2;
      assign zipWith_in2 = c$vec2[i*32+:32];
      wire signed [31:0] c$n;
      wire signed [31:0] result_5;
    wire signed [31:0] c$case_alt;
    wire [31:0] \r' ;
    wire [32:0] \c$r'_app_arg ;
    wire signed [32:0] r;
    wire [31:0] c$bv;
    wire [31:0] c$bv_0;
    wire [31:0] c$bv_1;
    wire [32:0] \r'_projection ;
    assign c$n = result_5;

    assign c$bv = (\r' );

    assign result_5 = ((( \c$r'_app_arg [33-1] ) ^ ( c$bv[32-1] )) == 1'b0) ? ($signed(\r' )) : c$case_alt;

    assign c$bv_0 = (($unsigned(zipWith_in2)));

    assign c$bv_1 = (($unsigned(zipWith_in1)));

    assign c$case_alt = ((( c$bv_0[32-1] ) & ( c$bv_1[32-1] )) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign \r'_projection  = \c$r'_app_arg ;

    assign \r'  = \r'_projection [31:0];

    assign \c$r'_app_arg  = ($unsigned(r));

    assign r = zipWith_in2 + zipWith_in1;


      assign ws1[i*32+:32] = c$n;
    end

    // zipWith end

    assign result_4 = $signed(ws[32-1:0]);

    // zipWith start
    genvar i_0;

    for (i_0 = 0; i_0 < 4; i_0 = i_0 + 1) begin : zipWith_0
      wire signed [31:0] zipWith_in1_0;
      assign zipWith_in1_0 = map_in[i_0*32+:32];
      wire  zipWith_in2_0;
      assign zipWith_in2_0 = eta[i_0*1+:1];
      wire signed [31:0] c$n_0;
      wire signed [31:0] result_6;
    assign c$n_0 = result_6;

    assign result_6 = zipWith_in2_0 ? zipWith_in1_0 : 32'sd0;


      assign c$ws1_app_arg[i_0*32+:32] = c$n_0;
    end

    // zipWith end


    assign c$results_app_arg[i_1*32+:32] = map_out;
  end
  endgenerate
  // map end

  // map begin
  genvar i_2;
  generate
  for (i_2=0; i_2 < 3; i_2 = i_2 + 1) begin : map_0
    wire [32:0] map_in_0;
    assign map_in_0 = results[i_2*33+:33];
    wire signed [31:0] map_out_0;
    assign map_out_0 = $signed(map_in_0[32:1]);


    assign c$ds1_app_arg[i_2*32+:32] = map_out_0;
  end
  endgenerate
  // map end

  // map begin
  genvar i_3;
  generate
  for (i_3=0; i_3 < 3; i_3 = i_3 + 1) begin : map_1
    wire [32:0] map_in_1;
    assign map_in_1 = results[i_3*33+:33];
    wire  map_out_1;
    assign map_out_1 = map_in_1[0:0];


    assign c$ds1_app_arg_0[i_3*1+:1] = map_out_1;
  end
  endgenerate
  // map end

  assign c$vec_0 = {{32'sd26214,   -32'sd13107,
                     32'sd39321},   {32'sd19660,   32'sd32768,
                                     -32'sd6553}};

  // map begin
  genvar i_6;
  generate
  for (i_6=0; i_6 < 2; i_6 = i_6 + 1) begin : map_2
    wire [95:0] map_in_2;
    assign map_in_2 = c$vec_0[i_6*96+:96];
    wire signed [31:0] map_out_2;
    wire [95:0] c$ws1_app_arg_0;
    wire signed [31:0] result_7;
    wire [127:0] ws_1;
    wire [95:0] ws1_0;
    wire [95:0] c$vec2_0;
    assign map_out_2 = result_7;

    // zipWith start
    genvar i_4;

    for (i_4 = 0; i_4 < 3; i_4 = i_4 + 1) begin : zipWith_1
      wire signed [31:0] zipWith_in1_1;
      assign zipWith_in1_1 = map_in_2[i_4*32+:32];
      wire  zipWith_in2_1;
      assign zipWith_in2_1 = c$ds1_app_arg_0[i_4*1+:1];
      wire signed [31:0] c$n_1;
      wire signed [31:0] result_8;
    assign c$n_1 = result_8;

    assign result_8 = zipWith_in2_1 ? zipWith_in1_1 : 32'sd0;


      assign c$ws1_app_arg_0[i_4*32+:32] = c$n_1;
    end

    // zipWith end

    assign result_7 = $signed(ws_1[32-1:0]);

    assign ws_1 = {32'sd0,   ws1_0};

    assign c$vec2_0 = (ws_1[128-1 : 32]);

    // zipWith start
    genvar i_5;

    for (i_5 = 0; i_5 < 3; i_5 = i_5 + 1) begin : zipWith_2
      wire signed [31:0] zipWith_in1_2;
      assign zipWith_in1_2 = c$ws1_app_arg_0[i_5*32+:32];
      wire signed [31:0] zipWith_in2_2;
      assign zipWith_in2_2 = c$vec2_0[i_5*32+:32];
      wire signed [31:0] c$n_2;
      wire signed [31:0] result_9;
    wire signed [31:0] c$case_alt_3;
    wire [31:0] \r'_1 ;
    wire [32:0] \c$r'_app_arg_0 ;
    wire signed [32:0] r_0;
    wire [31:0] c$bv_2;
    wire [31:0] c$bv_3;
    wire [31:0] c$bv_4;
    wire [32:0] \r'_projection_0 ;
    assign c$n_2 = result_9;

    assign c$bv_2 = (\r'_1 );

    assign result_9 = ((( \c$r'_app_arg_0 [33-1] ) ^ ( c$bv_2[32-1] )) == 1'b0) ? ($signed(\r'_1 )) : c$case_alt_3;

    assign c$bv_3 = (($unsigned(zipWith_in2_2)));

    assign c$bv_4 = (($unsigned(zipWith_in1_2)));

    assign c$case_alt_3 = ((( c$bv_3[32-1] ) & ( c$bv_4[32-1] )) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign \r'_projection_0  = \c$r'_app_arg_0 ;

    assign \r'_1  = \r'_projection_0 [31:0];

    assign \c$r'_app_arg_0  = ($unsigned(r_0));

    assign r_0 = zipWith_in2_2 + zipWith_in1_2;


      assign ws1_0[i_5*32+:32] = c$n_2;
    end

    // zipWith end


    assign c$results_app_arg_0[i_6*32+:32] = map_out_2;
  end
  endgenerate
  // map end

  // map begin
  genvar i_7;
  generate
  for (i_7=0; i_7 < 2; i_7 = i_7 + 1) begin : map_3
    wire [32:0] map_in_3;
    assign map_in_3 = results_0[i_7*33+:33];
    wire signed [31:0] map_out_3;
    assign map_out_3 = $signed(map_in_3[32:1]);


    assign c$ds2_app_arg[i_7*32+:32] = map_out_3;
  end
  endgenerate
  // map end

  // map begin
  genvar i_8;
  generate
  for (i_8=0; i_8 < 2; i_8 = i_8 + 1) begin : map_4
    wire [32:0] map_in_4;
    assign map_in_4 = results_0[i_8*33+:33];
    wire  map_out_4;
    assign map_out_4 = map_in_4[0:0];


    assign c$ds2_app_arg_0[i_8*1+:1] = map_out_4;
  end
  endgenerate
  // map end

  assign ds_1 = {{c$ds1_app_arg,
                  c$ds2_app_arg},   c$ds2_app_arg_0};

  // register begin
  always @(posedge clk or  posedge  rst) begin : ds_register
    if ( rst) begin
      ds <= {{32'sd0,   32'sd0,   32'sd0},   {32'sd0,   32'sd0}};
    end else if (en) begin
      ds <= ds_1[161:2];
    end
  end
  // register end

  assign sf = ds[159:64];

  assign sg = ds[63:0];

  // zipWith start
  genvar i_9;
  generate
  for (i_9 = 0; i_9 < 3; i_9 = i_9 + 1) begin : zipWith_3
    wire signed [31:0] zipWith_in1_3;
    assign zipWith_in1_3 = sf[i_9*32+:32];
    wire signed [31:0] zipWith_in2_3;
    assign zipWith_in2_3 = c$results_app_arg[i_9*32+:32];
    wire [32:0] c$n_3;
    wire signed [31:0] result_10;
    wire signed [31:0] c$case_alt_5;
    wire [31:0] \r'_2 ;
    wire [32:0] \c$r'_app_arg_1 ;
    wire signed [32:0] r_1;
    wire  fired;
    wire signed [31:0] c$app_arg;
    wire signed [31:0] result_11;
    wire signed [31:0] c$case_alt_6;
    wire [16:0] c$app_arg_0;
    wire [15:0] c$app_arg_1;
    wire [15:0] rL;
    wire [47:0] rR;
    wire [63:0] ds3;
    wire signed [63:0] c$ds3_app_arg;
    wire [32:0] c$case_alt_4;
    wire [31:0] c$bv_5;
    wire [31:0] c$bv_6;
    wire [31:0] c$bv_7;
    wire [32:0] \r'_projection_1 ;
    wire [47:0] c$bv_8;
    wire [47:0] c$bv_9;
    assign c$n_3 = c$case_alt_4;

    assign c$bv_5 = (\r'_2 );

    assign result_10 = ((( \c$r'_app_arg_1 [33-1] ) ^ ( c$bv_5[32-1] )) == 1'b0) ? ($signed(\r'_2 )) : c$case_alt_5;

    assign c$bv_6 = (($unsigned(result_11)));

    assign c$bv_7 = (($unsigned(zipWith_in2_3)));

    assign c$case_alt_5 = ((( c$bv_6[32-1] ) & ( c$bv_7[32-1] )) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign \r'_projection_1  = \c$r'_app_arg_1 ;

    assign \r'_2  = \r'_projection_1 [31:0];

    assign \c$r'_app_arg_1  = ($unsigned(r_1));

    assign r_1 = result_11 + zipWith_in2_3;

    assign fired = result_10 >= 32'sd65536;

    assign c$app_arg = fired ? 32'sd0 : result_10;

    assign c$bv_8 = (rR >> (64'sd16));

    assign result_11 = (((~ (| (c$app_arg_0))) | (& (c$app_arg_0))) == 1'b1) ? ($signed((c$bv_8[0+:32]))) : c$case_alt_6;

    assign c$case_alt_6 = (( c$app_arg_1[16-1] ) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign c$bv_9 = (rR);

    assign c$app_arg_0 = ({((( c$bv_9[48-1] ))),c$app_arg_1});

    assign c$app_arg_1 = rL;

    assign rL = ds3[63:48];

    assign rR = ds3[47:0];

    assign ds3 = (($unsigned(c$ds3_app_arg)));

    assign c$ds3_app_arg = 32'sd58982 * zipWith_in1_3;

    assign c$case_alt_4 = {c$app_arg,   fired};


    assign results[i_9*33+:33] = c$n_3;
  end
  endgenerate
  // zipWith end

  // zipWith start
  genvar i_10;
  generate
  for (i_10 = 0; i_10 < 2; i_10 = i_10 + 1) begin : zipWith_4
    wire signed [31:0] zipWith_in1_4;
    assign zipWith_in1_4 = sg[i_10*32+:32];
    wire signed [31:0] zipWith_in2_4;
    assign zipWith_in2_4 = c$results_app_arg_0[i_10*32+:32];
    wire [32:0] c$n_4;
    wire signed [31:0] result_12;
    wire signed [31:0] c$case_alt_8;
    wire [31:0] \r'_3 ;
    wire [32:0] \c$r'_app_arg_2 ;
    wire signed [32:0] r_2;
    wire  fired_0;
    wire signed [31:0] c$app_arg_5;
    wire signed [31:0] result_13;
    wire signed [31:0] c$case_alt_9;
    wire [16:0] c$app_arg_6;
    wire [15:0] c$app_arg_7;
    wire [15:0] rL_1;
    wire [47:0] rR_1;
    wire [63:0] ds3_0;
    wire signed [63:0] c$ds3_app_arg_0;
    wire [32:0] c$case_alt_7;
    wire [31:0] c$bv_10;
    wire [31:0] c$bv_11;
    wire [31:0] c$bv_12;
    wire [32:0] \r'_projection_2 ;
    wire [47:0] c$bv_13;
    wire [47:0] c$bv_14;
    assign c$n_4 = c$case_alt_7;

    assign c$bv_10 = (\r'_3 );

    assign result_12 = ((( \c$r'_app_arg_2 [33-1] ) ^ ( c$bv_10[32-1] )) == 1'b0) ? ($signed(\r'_3 )) : c$case_alt_8;

    assign c$bv_11 = (($unsigned(result_13)));

    assign c$bv_12 = (($unsigned(zipWith_in2_4)));

    assign c$case_alt_8 = ((( c$bv_11[32-1] ) & ( c$bv_12[32-1] )) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign \r'_projection_2  = \c$r'_app_arg_2 ;

    assign \r'_3  = \r'_projection_2 [31:0];

    assign \c$r'_app_arg_2  = ($unsigned(r_2));

    assign r_2 = result_13 + zipWith_in2_4;

    assign fired_0 = result_12 >= 32'sd65536;

    assign c$app_arg_5 = fired_0 ? 32'sd0 : result_12;

    assign c$bv_13 = (rR_1 >> (64'sd16));

    assign result_13 = (((~ (| (c$app_arg_6))) | (& (c$app_arg_6))) == 1'b1) ? ($signed((c$bv_13[0+:32]))) : c$case_alt_9;

    assign c$case_alt_9 = (( c$app_arg_7[16-1] ) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign c$bv_14 = (rR_1);

    assign c$app_arg_6 = ({((( c$bv_14[48-1] ))),c$app_arg_7});

    assign c$app_arg_7 = rL_1;

    assign rL_1 = ds3_0[63:48];

    assign rR_1 = ds3_0[47:0];

    assign ds3_0 = (($unsigned(c$ds3_app_arg_0)));

    assign c$ds3_app_arg_0 = 32'sd58982 * zipWith_in1_4;

    assign c$case_alt_7 = {c$app_arg_5,   fired_0};


    assign results_0[i_10*33+:33] = c$n_4;
  end
  endgenerate
  // zipWith end

  assign result_projection = {{c$ds1_app_arg,
                               c$ds2_app_arg},   c$ds2_app_arg_0};

  assign result = result_projection[1:0];

  assign result_0 = result[1:1];

  assign result_1 = result[0:0];


endmodule

