/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.4. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module snn12to7to5to3
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire  en // enable
    , input wire  eta_0
    , input wire  eta_1
    , input wire  eta_2
    , input wire  eta_3
    , input wire  eta_4
    , input wire  eta_5
    , input wire  eta_6
    , input wire  eta_7
    , input wire  eta_8
    , input wire  eta_9
    , input wire  eta_10
    , input wire  eta_11

      // Outputs
    , output wire  result_0
    , output wire  result_1
    , output wire  result_2
    );
  wire [223:0] c$results_app_arg;
  wire [223:0] c$ds1_app_arg;
  wire [6:0] c$ds1_app_arg_0;
  wire [159:0] c$results_app_arg_0;
  wire [159:0] c$ds2_app_arg;
  wire [4:0] c$ds2_app_arg_0;
  wire [95:0] c$results_app_arg_1;
  wire [95:0] c$ds2_app_arg_1;
  wire [2:0] c$ds2_app_arg_2;
  reg [479:0] ds = {{{32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0},
  {32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0}},   {32'sd0,   32'sd0,
                                                        32'sd0}};
  wire [383:0] sf;
  wire [95:0] sg;
  wire [223:0] sf_0;
  wire [159:0] sg_0;
  wire [98:0] results;
  wire [164:0] results_0;
  wire [230:0] results_1;
  wire [11:0] eta;
  wire [2687:0] c$vec;
  wire [1119:0] c$vec_0;
  wire [479:0] c$vec_1;
  wire [482:0] ds_1;
  wire [482:0] result_projection;
  wire [2:0] result;

  assign eta = {eta_0,   eta_1,   eta_2,
                eta_3,   eta_4,   eta_5,   eta_6,   eta_7,
                eta_8,   eta_9,   eta_10,   eta_11};

  assign c$vec = {{32'sd16384,   -32'sd6553,
                   32'sd9830,   32'sd0,   32'sd13107,
                   -32'sd3276,   32'sd6553,   32'sd19660,
                   -32'sd7864,   32'sd11796,   32'sd0,
                   32'sd14417},   {-32'sd11796,   32'sd15728,
                                   32'sd0,   32'sd7864,   32'sd5242,
                                   32'sd10485,   -32'sd9175,   32'sd18350,
                                   32'sd7208,   32'sd0,   32'sd13107,
                                   -32'sd3932},   {32'sd3276,   32'sd12451,
                                                   -32'sd14417,   32'sd20316,   32'sd0,
                                                   32'sd9175,   32'sd17039,   -32'sd5898,
                                                   32'sd11141,   32'sd4587,   -32'sd2621,
                                                   32'sd7864},   {32'sd19005,   32'sd0,
                                                                  32'sd8519,   -32'sd11141,   32'sd13762,
                                                                  32'sd5898,   32'sd0,   32'sd15728,
                                                                  -32'sd5242,   32'sd10485,   32'sd3932,
                                                                  -32'sd7208},   {-32'sd4587,   32'sd17694,
                                                                                  32'sd11796,   32'sd0,   -32'sd9830,
                                                                                  32'sd15073,   32'sd7864,   32'sd3276,
                                                                                  32'sd12451,   -32'sd6553,
                                                                                  32'sd9175,   32'sd0},   {32'sd7208,
                                                                                                           32'sd2621,
                                                                                                           32'sd16384,
                                                                                                           -32'sd8519,
                                                                                                           32'sd18350,
                                                                                                           32'sd0,
                                                                                                           32'sd5898,
                                                                                                           -32'sd10485,
                                                                                                           32'sd14417,
                                                                                                           32'sd9830,
                                                                                                           32'sd1966,
                                                                                                           32'sd11796},
                  {32'sd0,   32'sd13762,   -32'sd3276,
                   32'sd11796,   32'sd15728,   32'sd6553,
                   -32'sd5898,   32'sd8519,   32'sd0,
                   32'sd13107,   32'sd10485,   -32'sd7864}};

  // map begin
  genvar i_1;
  generate
  for (i_1=0; i_1 < 7; i_1 = i_1 + 1) begin : map
    wire [383:0] map_in;
    assign map_in = c$vec[i_1*384+:384];
    wire signed [31:0] map_out;
    wire [415:0] ws;
    wire [383:0] ws1;
    wire signed [31:0] result_6;
    wire [383:0] c$ws1_app_arg;
    wire [383:0] c$vec2;
    assign map_out = result_6;

    assign ws = {32'sd0,   ws1};

    assign c$vec2 = (ws[416-1 : 32]);

    // zipWith start
    genvar i;

    for (i = 0; i < 12; i = i + 1) begin : zipWith
      wire signed [31:0] zipWith_in1;
      assign zipWith_in1 = c$ws1_app_arg[i*32+:32];
      wire signed [31:0] zipWith_in2;
      assign zipWith_in2 = c$vec2[i*32+:32];
      wire signed [31:0] c$n;
      wire signed [31:0] result_7;
    wire signed [31:0] c$case_alt;
    wire [31:0] \r' ;
    wire [32:0] \c$r'_app_arg ;
    wire signed [32:0] r;
    wire [31:0] c$bv;
    wire [31:0] c$bv_0;
    wire [31:0] c$bv_1;
    wire [32:0] \r'_projection ;
    assign c$n = result_7;

    assign c$bv = (\r' );

    assign result_7 = ((( \c$r'_app_arg [33-1] ) ^ ( c$bv[32-1] )) == 1'b0) ? ($signed(\r' )) : c$case_alt;

    assign c$bv_0 = (($unsigned(zipWith_in2)));

    assign c$bv_1 = (($unsigned(zipWith_in1)));

    assign c$case_alt = ((( c$bv_0[32-1] ) & ( c$bv_1[32-1] )) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign \r'_projection  = \c$r'_app_arg ;

    assign \r'  = \r'_projection [31:0];

    assign \c$r'_app_arg  = ($unsigned(r));

    assign r = zipWith_in2 + zipWith_in1;


      assign ws1[i*32+:32] = c$n;
    end

    // zipWith end

    assign result_6 = $signed(ws[32-1:0]);

    // zipWith start
    genvar i_0;

    for (i_0 = 0; i_0 < 12; i_0 = i_0 + 1) begin : zipWith_0
      wire signed [31:0] zipWith_in1_0;
      assign zipWith_in1_0 = map_in[i_0*32+:32];
      wire  zipWith_in2_0;
      assign zipWith_in2_0 = eta[i_0*1+:1];
      wire signed [31:0] c$n_0;
      wire signed [31:0] result_8;
    assign c$n_0 = result_8;

    assign result_8 = zipWith_in2_0 ? zipWith_in1_0 : 32'sd0;


      assign c$ws1_app_arg[i_0*32+:32] = c$n_0;
    end

    // zipWith end


    assign c$results_app_arg[i_1*32+:32] = map_out;
  end
  endgenerate
  // map end

  // map begin
  genvar i_2;
  generate
  for (i_2=0; i_2 < 7; i_2 = i_2 + 1) begin : map_0
    wire [32:0] map_in_0;
    assign map_in_0 = results_1[i_2*33+:33];
    wire signed [31:0] map_out_0;
    assign map_out_0 = $signed(map_in_0[32:1]);


    assign c$ds1_app_arg[i_2*32+:32] = map_out_0;
  end
  endgenerate
  // map end

  // map begin
  genvar i_3;
  generate
  for (i_3=0; i_3 < 7; i_3 = i_3 + 1) begin : map_1
    wire [32:0] map_in_1;
    assign map_in_1 = results_1[i_3*33+:33];
    wire  map_out_1;
    assign map_out_1 = map_in_1[0:0];


    assign c$ds1_app_arg_0[i_3*1+:1] = map_out_1;
  end
  endgenerate
  // map end

  assign c$vec_0 = {{32'sd19660,   -32'sd11796,
                     32'sd14417,   32'sd0,   32'sd9175,
                     32'sd12451,   -32'sd7208},   {-32'sd5898,
                                                   32'sd17694,   32'sd10485,   32'sd13762,
                                                   32'sd0,   -32'sd8519,   32'sd15728},
                    {32'sd11796,   32'sd0,   -32'sd9830,
                     32'sd17039,   32'sd7864,   32'sd13107,
                     32'sd4587},   {32'sd3276,   32'sd15073,
                                    32'sd7208,   -32'sd11141,   32'sd19005,
                                    32'sd0,   32'sd9830},   {-32'sd7864,
                                                             32'sd9175,   32'sd16384,   32'sd5898,
                                                             32'sd11796,   -32'sd5242,   32'sd14417}};

  // map begin
  genvar i_6;
  generate
  for (i_6=0; i_6 < 5; i_6 = i_6 + 1) begin : map_2
    wire [223:0] map_in_2;
    assign map_in_2 = c$vec_0[i_6*224+:224];
    wire signed [31:0] map_out_2;
    wire [223:0] c$ws1_app_arg_0;
    wire signed [31:0] result_9;
    wire [255:0] ws_1;
    wire [223:0] ws1_0;
    wire [223:0] c$vec2_0;
    assign map_out_2 = result_9;

    // zipWith start
    genvar i_4;

    for (i_4 = 0; i_4 < 7; i_4 = i_4 + 1) begin : zipWith_1
      wire signed [31:0] zipWith_in1_1;
      assign zipWith_in1_1 = map_in_2[i_4*32+:32];
      wire  zipWith_in2_1;
      assign zipWith_in2_1 = c$ds1_app_arg_0[i_4*1+:1];
      wire signed [31:0] c$n_1;
      wire signed [31:0] result_10;
    assign c$n_1 = result_10;

    assign result_10 = zipWith_in2_1 ? zipWith_in1_1 : 32'sd0;


      assign c$ws1_app_arg_0[i_4*32+:32] = c$n_1;
    end

    // zipWith end

    assign result_9 = $signed(ws_1[32-1:0]);

    assign ws_1 = {32'sd0,   ws1_0};

    assign c$vec2_0 = (ws_1[256-1 : 32]);

    // zipWith start
    genvar i_5;

    for (i_5 = 0; i_5 < 7; i_5 = i_5 + 1) begin : zipWith_2
      wire signed [31:0] zipWith_in1_2;
      assign zipWith_in1_2 = c$ws1_app_arg_0[i_5*32+:32];
      wire signed [31:0] zipWith_in2_2;
      assign zipWith_in2_2 = c$vec2_0[i_5*32+:32];
      wire signed [31:0] c$n_2;
      wire signed [31:0] result_11;
    wire signed [31:0] c$case_alt_3;
    wire [31:0] \r'_1 ;
    wire [32:0] \c$r'_app_arg_0 ;
    wire signed [32:0] r_0;
    wire [31:0] c$bv_2;
    wire [31:0] c$bv_3;
    wire [31:0] c$bv_4;
    wire [32:0] \r'_projection_0 ;
    assign c$n_2 = result_11;

    assign c$bv_2 = (\r'_1 );

    assign result_11 = ((( \c$r'_app_arg_0 [33-1] ) ^ ( c$bv_2[32-1] )) == 1'b0) ? ($signed(\r'_1 )) : c$case_alt_3;

    assign c$bv_3 = (($unsigned(zipWith_in2_2)));

    assign c$bv_4 = (($unsigned(zipWith_in1_2)));

    assign c$case_alt_3 = ((( c$bv_3[32-1] ) & ( c$bv_4[32-1] )) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign \r'_projection_0  = \c$r'_app_arg_0 ;

    assign \r'_1  = \r'_projection_0 [31:0];

    assign \c$r'_app_arg_0  = ($unsigned(r_0));

    assign r_0 = zipWith_in2_2 + zipWith_in1_2;


      assign ws1_0[i_5*32+:32] = c$n_2;
    end

    // zipWith end


    assign c$results_app_arg_0[i_6*32+:32] = map_out_2;
  end
  endgenerate
  // map end

  // map begin
  genvar i_7;
  generate
  for (i_7=0; i_7 < 5; i_7 = i_7 + 1) begin : map_3
    wire [32:0] map_in_3;
    assign map_in_3 = results_0[i_7*33+:33];
    wire signed [31:0] map_out_3;
    assign map_out_3 = $signed(map_in_3[32:1]);


    assign c$ds2_app_arg[i_7*32+:32] = map_out_3;
  end
  endgenerate
  // map end

  // map begin
  genvar i_8;
  generate
  for (i_8=0; i_8 < 5; i_8 = i_8 + 1) begin : map_4
    wire [32:0] map_in_4;
    assign map_in_4 = results_0[i_8*33+:33];
    wire  map_out_4;
    assign map_out_4 = map_in_4[0:0];


    assign c$ds2_app_arg_0[i_8*1+:1] = map_out_4;
  end
  endgenerate
  // map end

  assign c$vec_1 = {{32'sd22282,   -32'sd10485,
                     32'sd13762,   32'sd0,   32'sd11796},
                    {32'sd5898,   32'sd18350,   -32'sd9175,
                     32'sd15728,   32'sd7208},   {-32'sd6553,
                                                  32'sd11141,   32'sd17039,   32'sd8519,
                                                  32'sd13107}};

  // map begin
  genvar i_11;
  generate
  for (i_11=0; i_11 < 3; i_11 = i_11 + 1) begin : map_5
    wire [159:0] map_in_5;
    assign map_in_5 = c$vec_1[i_11*160+:160];
    wire signed [31:0] map_out_5;
    wire [159:0] c$ws1_app_arg_1;
    wire signed [31:0] result_12;
    wire [191:0] ws_2;
    wire [159:0] ws1_1;
    wire [159:0] c$vec2_1;
    assign map_out_5 = result_12;

    // zipWith start
    genvar i_9;

    for (i_9 = 0; i_9 < 5; i_9 = i_9 + 1) begin : zipWith_3
      wire signed [31:0] zipWith_in1_3;
      assign zipWith_in1_3 = map_in_5[i_9*32+:32];
      wire  zipWith_in2_3;
      assign zipWith_in2_3 = c$ds2_app_arg_0[i_9*1+:1];
      wire signed [31:0] c$n_3;
      wire signed [31:0] result_13;
    assign c$n_3 = result_13;

    assign result_13 = zipWith_in2_3 ? zipWith_in1_3 : 32'sd0;


      assign c$ws1_app_arg_1[i_9*32+:32] = c$n_3;
    end

    // zipWith end

    assign result_12 = $signed(ws_2[32-1:0]);

    assign ws_2 = {32'sd0,   ws1_1};

    assign c$vec2_1 = (ws_2[192-1 : 32]);

    // zipWith start
    genvar i_10;

    for (i_10 = 0; i_10 < 5; i_10 = i_10 + 1) begin : zipWith_4
      wire signed [31:0] zipWith_in1_4;
      assign zipWith_in1_4 = c$ws1_app_arg_1[i_10*32+:32];
      wire signed [31:0] zipWith_in2_4;
      assign zipWith_in2_4 = c$vec2_1[i_10*32+:32];
      wire signed [31:0] c$n_4;
      wire signed [31:0] result_14;
    wire signed [31:0] c$case_alt_4;
    wire [31:0] \r'_2 ;
    wire [32:0] \c$r'_app_arg_1 ;
    wire signed [32:0] r_1;
    wire [31:0] c$bv_5;
    wire [31:0] c$bv_6;
    wire [31:0] c$bv_7;
    wire [32:0] \r'_projection_1 ;
    assign c$n_4 = result_14;

    assign c$bv_5 = (\r'_2 );

    assign result_14 = ((( \c$r'_app_arg_1 [33-1] ) ^ ( c$bv_5[32-1] )) == 1'b0) ? ($signed(\r'_2 )) : c$case_alt_4;

    assign c$bv_6 = (($unsigned(zipWith_in2_4)));

    assign c$bv_7 = (($unsigned(zipWith_in1_4)));

    assign c$case_alt_4 = ((( c$bv_6[32-1] ) & ( c$bv_7[32-1] )) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign \r'_projection_1  = \c$r'_app_arg_1 ;

    assign \r'_2  = \r'_projection_1 [31:0];

    assign \c$r'_app_arg_1  = ($unsigned(r_1));

    assign r_1 = zipWith_in2_4 + zipWith_in1_4;


      assign ws1_1[i_10*32+:32] = c$n_4;
    end

    // zipWith end


    assign c$results_app_arg_1[i_11*32+:32] = map_out_5;
  end
  endgenerate
  // map end

  // map begin
  genvar i_12;
  generate
  for (i_12=0; i_12 < 3; i_12 = i_12 + 1) begin : map_6
    wire [32:0] map_in_6;
    assign map_in_6 = results[i_12*33+:33];
    wire signed [31:0] map_out_6;
    assign map_out_6 = $signed(map_in_6[32:1]);


    assign c$ds2_app_arg_1[i_12*32+:32] = map_out_6;
  end
  endgenerate
  // map end

  // map begin
  genvar i_13;
  generate
  for (i_13=0; i_13 < 3; i_13 = i_13 + 1) begin : map_7
    wire [32:0] map_in_7;
    assign map_in_7 = results[i_13*33+:33];
    wire  map_out_7;
    assign map_out_7 = map_in_7[0:0];


    assign c$ds2_app_arg_2[i_13*1+:1] = map_out_7;
  end
  endgenerate
  // map end

  assign ds_1 = {{{c$ds1_app_arg,
                   c$ds2_app_arg},   c$ds2_app_arg_1},
                 c$ds2_app_arg_2};

  // register begin
  always @(posedge clk or  posedge  rst) begin : ds_register
    if ( rst) begin
      ds <= {{{32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0},
    {32'sd0,   32'sd0,   32'sd0,   32'sd0,   32'sd0}},   {32'sd0,   32'sd0,
                                                          32'sd0}};
    end else if (en) begin
      ds <= ds_1[482:3];
    end
  end
  // register end

  assign sf = ds[479:96];

  assign sg = ds[95:0];

  assign sf_0 = sf[383:160];

  assign sg_0 = sf[159:0];

  // zipWith start
  genvar i_14;
  generate
  for (i_14 = 0; i_14 < 3; i_14 = i_14 + 1) begin : zipWith_5
    wire signed [31:0] zipWith_in1_5;
    assign zipWith_in1_5 = sg[i_14*32+:32];
    wire signed [31:0] zipWith_in2_5;
    assign zipWith_in2_5 = c$results_app_arg_1[i_14*32+:32];
    wire [32:0] c$n_5;
    wire signed [31:0] result_15;
    wire signed [31:0] c$case_alt_6;
    wire [31:0] \r'_3 ;
    wire [32:0] \c$r'_app_arg_2 ;
    wire signed [32:0] r_2;
    wire  fired;
    wire signed [31:0] c$app_arg;
    wire signed [31:0] result_16;
    wire signed [31:0] c$case_alt_7;
    wire [16:0] c$app_arg_0;
    wire [15:0] c$app_arg_1;
    wire [15:0] rL;
    wire [47:0] rR;
    wire [63:0] ds3;
    wire signed [63:0] c$ds3_app_arg;
    wire [32:0] c$case_alt_5;
    wire [31:0] c$bv_8;
    wire [31:0] c$bv_9;
    wire [31:0] c$bv_10;
    wire [32:0] \r'_projection_2 ;
    wire [47:0] c$bv_11;
    wire [47:0] c$bv_12;
    assign c$n_5 = c$case_alt_5;

    assign c$bv_8 = (\r'_3 );

    assign result_15 = ((( \c$r'_app_arg_2 [33-1] ) ^ ( c$bv_8[32-1] )) == 1'b0) ? ($signed(\r'_3 )) : c$case_alt_6;

    assign c$bv_9 = (($unsigned(result_16)));

    assign c$bv_10 = (($unsigned(zipWith_in2_5)));

    assign c$case_alt_6 = ((( c$bv_9[32-1] ) & ( c$bv_10[32-1] )) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign \r'_projection_2  = \c$r'_app_arg_2 ;

    assign \r'_3  = \r'_projection_2 [31:0];

    assign \c$r'_app_arg_2  = ($unsigned(r_2));

    assign r_2 = result_16 + zipWith_in2_5;

    assign fired = result_15 >= 32'sd52428;

    assign c$app_arg = fired ? 32'sd0 : result_15;

    assign c$bv_11 = (rR >> (64'sd16));

    assign result_16 = (((~ (| (c$app_arg_0))) | (& (c$app_arg_0))) == 1'b1) ? ($signed((c$bv_11[0+:32]))) : c$case_alt_7;

    assign c$case_alt_7 = (( c$app_arg_1[16-1] ) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign c$bv_12 = (rR);

    assign c$app_arg_0 = ({((( c$bv_12[48-1] ))),c$app_arg_1});

    assign c$app_arg_1 = rL;

    assign rL = ds3[63:48];

    assign rR = ds3[47:0];

    assign ds3 = (($unsigned(c$ds3_app_arg)));

    assign c$ds3_app_arg = 32'sd60293 * zipWith_in1_5;

    assign c$case_alt_5 = {c$app_arg,   fired};


    assign results[i_14*33+:33] = c$n_5;
  end
  endgenerate
  // zipWith end

  // zipWith start
  genvar i_15;
  generate
  for (i_15 = 0; i_15 < 5; i_15 = i_15 + 1) begin : zipWith_6
    wire signed [31:0] zipWith_in1_6;
    assign zipWith_in1_6 = sg_0[i_15*32+:32];
    wire signed [31:0] zipWith_in2_6;
    assign zipWith_in2_6 = c$results_app_arg_0[i_15*32+:32];
    wire [32:0] c$n_6;
    wire signed [31:0] result_17;
    wire signed [31:0] c$case_alt_9;
    wire [31:0] \r'_4 ;
    wire [32:0] \c$r'_app_arg_3 ;
    wire signed [32:0] r_3;
    wire  fired_0;
    wire signed [31:0] c$app_arg_5;
    wire signed [31:0] result_18;
    wire signed [31:0] c$case_alt_10;
    wire [16:0] c$app_arg_6;
    wire [15:0] c$app_arg_7;
    wire [15:0] rL_1;
    wire [47:0] rR_1;
    wire [63:0] ds3_0;
    wire signed [63:0] c$ds3_app_arg_0;
    wire [32:0] c$case_alt_8;
    wire [31:0] c$bv_13;
    wire [31:0] c$bv_14;
    wire [31:0] c$bv_15;
    wire [32:0] \r'_projection_3 ;
    wire [47:0] c$bv_16;
    wire [47:0] c$bv_17;
    assign c$n_6 = c$case_alt_8;

    assign c$bv_13 = (\r'_4 );

    assign result_17 = ((( \c$r'_app_arg_3 [33-1] ) ^ ( c$bv_13[32-1] )) == 1'b0) ? ($signed(\r'_4 )) : c$case_alt_9;

    assign c$bv_14 = (($unsigned(result_18)));

    assign c$bv_15 = (($unsigned(zipWith_in2_6)));

    assign c$case_alt_9 = ((( c$bv_14[32-1] ) & ( c$bv_15[32-1] )) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign \r'_projection_3  = \c$r'_app_arg_3 ;

    assign \r'_4  = \r'_projection_3 [31:0];

    assign \c$r'_app_arg_3  = ($unsigned(r_3));

    assign r_3 = result_18 + zipWith_in2_6;

    assign fired_0 = result_17 >= 32'sd52428;

    assign c$app_arg_5 = fired_0 ? 32'sd0 : result_17;

    assign c$bv_16 = (rR_1 >> (64'sd16));

    assign result_18 = (((~ (| (c$app_arg_6))) | (& (c$app_arg_6))) == 1'b1) ? ($signed((c$bv_16[0+:32]))) : c$case_alt_10;

    assign c$case_alt_10 = (( c$app_arg_7[16-1] ) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign c$bv_17 = (rR_1);

    assign c$app_arg_6 = ({((( c$bv_17[48-1] ))),c$app_arg_7});

    assign c$app_arg_7 = rL_1;

    assign rL_1 = ds3_0[63:48];

    assign rR_1 = ds3_0[47:0];

    assign ds3_0 = (($unsigned(c$ds3_app_arg_0)));

    assign c$ds3_app_arg_0 = 32'sd60293 * zipWith_in1_6;

    assign c$case_alt_8 = {c$app_arg_5,   fired_0};


    assign results_0[i_15*33+:33] = c$n_6;
  end
  endgenerate
  // zipWith end

  // zipWith start
  genvar i_16;
  generate
  for (i_16 = 0; i_16 < 7; i_16 = i_16 + 1) begin : zipWith_7
    wire signed [31:0] zipWith_in1_7;
    assign zipWith_in1_7 = sf_0[i_16*32+:32];
    wire signed [31:0] zipWith_in2_7;
    assign zipWith_in2_7 = c$results_app_arg[i_16*32+:32];
    wire [32:0] c$n_7;
    wire signed [31:0] result_19;
    wire signed [31:0] c$case_alt_12;
    wire [31:0] \r'_5 ;
    wire [32:0] \c$r'_app_arg_4 ;
    wire signed [32:0] r_4;
    wire  fired_1;
    wire signed [31:0] c$app_arg_8;
    wire signed [31:0] result_20;
    wire signed [31:0] c$case_alt_13;
    wire [16:0] c$app_arg_9;
    wire [15:0] c$app_arg_10;
    wire [15:0] rL_2;
    wire [47:0] rR_2;
    wire [63:0] ds3_1;
    wire signed [63:0] c$ds3_app_arg_1;
    wire [32:0] c$case_alt_11;
    wire [31:0] c$bv_18;
    wire [31:0] c$bv_19;
    wire [31:0] c$bv_20;
    wire [32:0] \r'_projection_4 ;
    wire [47:0] c$bv_21;
    wire [47:0] c$bv_22;
    assign c$n_7 = c$case_alt_11;

    assign c$bv_18 = (\r'_5 );

    assign result_19 = ((( \c$r'_app_arg_4 [33-1] ) ^ ( c$bv_18[32-1] )) == 1'b0) ? ($signed(\r'_5 )) : c$case_alt_12;

    assign c$bv_19 = (($unsigned(result_20)));

    assign c$bv_20 = (($unsigned(zipWith_in2_7)));

    assign c$case_alt_12 = ((( c$bv_19[32-1] ) & ( c$bv_20[32-1] )) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign \r'_projection_4  = \c$r'_app_arg_4 ;

    assign \r'_5  = \r'_projection_4 [31:0];

    assign \c$r'_app_arg_4  = ($unsigned(r_4));

    assign r_4 = result_20 + zipWith_in2_7;

    assign fired_1 = result_19 >= 32'sd52428;

    assign c$app_arg_8 = fired_1 ? 32'sd0 : result_19;

    assign c$bv_21 = (rR_2 >> (64'sd16));

    assign result_20 = (((~ (| (c$app_arg_9))) | (& (c$app_arg_9))) == 1'b1) ? ($signed((c$bv_21[0+:32]))) : c$case_alt_13;

    assign c$case_alt_13 = (( c$app_arg_10[16-1] ) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

    assign c$bv_22 = (rR_2);

    assign c$app_arg_9 = ({((( c$bv_22[48-1] ))),c$app_arg_10});

    assign c$app_arg_10 = rL_2;

    assign rL_2 = ds3_1[63:48];

    assign rR_2 = ds3_1[47:0];

    assign ds3_1 = (($unsigned(c$ds3_app_arg_1)));

    assign c$ds3_app_arg_1 = 32'sd60293 * zipWith_in1_7;

    assign c$case_alt_11 = {c$app_arg_8,   fired_1};


    assign results_1[i_16*33+:33] = c$n_7;
  end
  endgenerate
  // zipWith end

  assign result_projection = {{{c$ds1_app_arg,
                                c$ds2_app_arg},   c$ds2_app_arg_1},
                              c$ds2_app_arg_2};

  assign result = result_projection[2:0];

  assign result_0 = result[2:2];

  assign result_1 = result[1:1];

  assign result_2 = result[0:0];


endmodule

